name: Building and testing

on:
  push:
    branches:
      - '**'

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: npm i --legacy-peer-deps


      - name: test esLint
        run: npm run lint
